services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: ${PORT}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        source: ./leveldb
        target: /usr/src/app/leveldb
volumes:
  leveldb:
